### ISSUE TITLE
Script execution from a different path

### ISSUE THREAD

**Issue by nosqlgeek** [redislabs-training/slides-as-code-setup#4]
I am getting the following error message when trying to excute 'rls' from a different path:

```
../rls.sh: line 2: config.sh: No such file or directory
57dff5fb1527ac018b2f942f123de1e70b2ed0432ca37de017b61bd2e9e2ddfa
You presentation presentation.md was initialised successfully. Serve it by running ./rls.sh serve and Have fun!
```
It should be possible to run the command in a way that it can be executed from any path. This would allow to have a truely global installation of it.

**Comment by elena-kolevska** [comment]
Fixed by @nosqlgeek . Closing.
